[colors.primary]
background = '#1a1a1a'
foreground = '#ebdbb2'

[window]
opacity = 1.0

[terminal]
# shell = {program = "zsh", args = []}
# shell = {program = "nvim", args = ["--cmd 'term'"]}
shell = {program = "nvim", args = []}

[mouse]
hide_when_typing = true

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[scrolling]
history = 100000

[env]
ALC_FONT = "JetBrainsMono NFM"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"
